apiVersion: v1
kind: Service
metadata:
  name: my-app-clusterip  
  labels:
    {{ include "my-app.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "my-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-nodeport
spec:
  selector:
    app: {{ include "my-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort